hyper-parameters:
  batch_size: 30
  epochs: 30
  pred_window_size: [64,48]
  penalty_factor: 1.
  stride: 24
  layers_3D: 1
image-data:
  samples_per_image: 200
  n_test_files: 3
  pre_process: !!bool True
network:
  size: small
classifier:
  classifier: "membrane"
weights:
  load_n_layers: -1
main:
    ID_folder: test
