hyper-parameters:
  batch_size: 30
  epochs: 30
  in_window_shape: [64,64]
  out_window_shape: [48,48]
  penalty_factor: 1.
  stride: 12
image-data:
  samples_per_image: 200
  n_test_files: 3 
  layers_3D: 1
convolution:
  size: small
classifier:
  classifier: "membrane"
load-weights:
  load_n_layers: -1
main:
    ID_folder: test
pre-process:
    pre_process: !!bool True
