convolution:
  size: large
  directory_input: ['data/train-input','data/AC3-input']
  directory_labels: ['data/train-labels','data/AC3-labels']
classifier:
  classifier: 'synapse_reg'
  load_n_layers: 5
pre-process:
  pre_process_only: True
  pre_process: True
convolution:
  size: "large"
load-weights:
  load_n_layers: -1