hyper-parameters:
  in_window_shape: [64,64]
  out_window_shape: [12,12]
  stride: 6
image-data:
  samples_per_image: 50
convolution:
  size: large
  directory_input:  ['data/AC3-input']  #['data/train-input']
  directory_labels: ['data/AC3-labels'] #['data/train-labels']
classifier:
  classifier: "synapse_reg"
load-weights:
  load_n_layers: -1
pre-process:
    pre_process: !!bool False
