hyper-parameters:
  batch_size: 30
  epochs: 30
  in_window_shape: [64,64]
  out_window_shape: [12,12]
  penalty_factor: 0.
  stride: 2
image-data:
  samples_per_image: 1000
  n_test_files: 3 
  layers_3D: 1
convolution:
  size: small
classifier:
  classifier: "membrane"
load-weights:
  load_n_layers: -1
<<<<<<< HEAD
main:
    ID_folder: test
=======
pre-process:
    pre_process: !!bool True
>>>>>>> 8551c69399b72a8c7005449f7d94ce78db48600d
