hyper-parameters:
  in_window_shape: [128,128]
  out_window_shape: [12,12]
  stride: 6
image-data:
  samples_per_image: 100
convolution:
  size: large
  directory_input: ['data/train-input','data/AC3-input']
  directory_labels: ['data/train-labels','data/AC3-labels']
classifier:
  classifier: 'synapse_reg'
  load_n_layers: 5
load-weights:
  load_n_layers: -1