per-parameters:
  batch_size: 30
  epochs: 30
  in_window_shape: [64,64]
  out_window_shape: [12,12]
  penatly_factor: 0.
  maxoutsize: [1,1,1]
  stride: 12
image-data:
  n_test_files: 10
  layers_3D: 3
classifier:
  classifier: 'synapse_reg'
load-weights:
  load_n_layers: 5
weights_path: 
  weights_path: 'parameters/params.dat'
convolution:
  size: large
  directory_input: ['data/train-input','data/AC3-input']
  directory_labels: ['data/train-labels','data/AC3-labels']
pre-process:
  pre_process: False
